services:
  postgres:
    image: postgres:17
    container_name: releasepilot-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: releasepilot
      POSTGRES_USER: releasepilot
      POSTGRES_PASSWORD: releasepilot

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
